### ISSUE TITLE
User Testing (10-1-2019)

### ISSUE THREAD

**Issue by mhmdtshref** [FACK1/Familia#1]
First test of the app, user testing results should be on the comments.

**Comment by orjwan98** [comment]
**User's name: little boy**
**main issues: **
1- language barrier. 
2- App isn’t self-explanatory. (what the app does)
3- App isn’t easily navigate-able. (e.g: elements aren’t very clear on what they do/can do)

**Comment by orjwan98** [comment]
**User’s name: Haneen**
**main issues: **
1- language barrier. 
2- App isn’t self-explanatory. (what the app does)

**Comment by orjwan98** [comment]
**User’s name: Ramzi**
**main issues:** 
1- language barrier. 
2- App isn’t self-explanatory. (what the app does).
3- App isn’t easily navigate-able. (e.g: elements aren’t very clear on what they do/can do)
**some suggestions:**
4- Thinks app idea is good and smart: but doesn’t know if it can be applied here. Maybe make an Arabic version too?
5- Filter items according to status, e.g: in progress, done.

**Comment by fdo2** [comment]
**User's name: An'am**

**Opinions and suggestions:**

1.  App isn’t navigable enough.
2.  Need a home (may be in logo) & back buttons.
3.  Name and tagline are not clear enough, & suggested that we can use a subtitle like “ share your shopping list”
4.  Need icons to show that item is clickable.
5.  you can use an items category & showing items status, also labeling items that assigned to someone.
6.  logo needs to have something to do with what the app does.
7.  keep track of what being bought for certain time e.g: a week, & automatically delete entries list after a while.
8.  special list: something you always buy , e.g: bread, or something you only need once, e.g: biethday cake.
9. allow user to join more than one family.

**Comment by mhmdtshref** [comment]
## User name: Anas Sarabta
### Main points:
- Don't understand app
### User profile:
He is an employee on YDRC.
### Suggestions:
- Don't know why the app is for, but when read understand.
- interface is not working sometime.
- User interface need to be easier.
- another social apps can be helpful to get the same goal of the app.
- usually one person get things from outside, so we need to take a photo of list of things and send it to him.
### Suggestions:
- Add options like 'what to cook today?' and have some options family members vote for.
- Style need to be changed, we are using Web101.
