### ISSUE TITLE
User Testing (23-1-2019)

### ISSUE THREAD

**Issue by orjwan98** [FACK1/Familia#39]
Second test of the app (after the 1st sprint). User testing results should be on the comments.

**Comment by fdo2** [comment]
## User name: Ghassan Maslamani
### User profile:
GSG mentor.
### Main points:
- Doesn't know what app is for at first glance.
- Extra features are needed to know who's assigned to what.
- Green means sth?
### Suggestions:
- Logout needs to be more visible !

**Comment by orjwan98** [comment]
**User's name: Shahenaz**
**Occupation: Web developer and mentor**
**main issues:**
1- _Join family_ isn't very clear on what it does. It isn't obvious to anew user what joining a family means.
2- Settings doesn't fit its context very well.
 **Suggestions**
1- For settings, consider adding more features to it or change what the button says.

**Comment by orjwan98** [comment]
**User's name: Amjad**
**Occupation: YDRC supervisor**
**main issues:**
1- Language barrier.
2- Seemed to think that the green means something. Even though it's decoration.

**Comment by fdo2** [comment]
**User's name: Haneen**
**Occupation: YDRC employee**
**main issues:**
1-She went straight to login (More a language barrier)
2- Had to explain what to do i.e. create a family
